import pandas as pd

def makeTable(subjectDataPath, objectivesDataFrame):
    subjectsDF = pd.read_csv(subjectDataPath)
    objectivesDF = objectivesDataFrame

    # Merge the two DataFrames
    mergedDF = pd.merge(subjectsDF, objectivesDF, left_on='Codigo Materia', right_on='Codigo', how='inner')
    mergedDF.drop(columns=['Codigo'], inplace=True)
    
    return mergedDF


# Mock data
data = {
    "Codigo": ["CIEHT06", "PSOHT04", "ECO0505", "BIO1001", "ECO0605"],
    "S": ["Sí.\nEl objetivo es bastante claro en cuanto a lo que se quiere lograr: una comprensión técnica del impacto ambiental en obras civiles, junto con la aplicación de normativa y estrategias de mitigación.", "Sí.\nEl objetivo es bastante claro en cuanto a lo que se quiere lograr: una comprensión técnica del impacto ambiental en obras civiles, junto con la aplicación de normativa y estrategias de mitigación.", "Sí.\nEl objetivo es bastante claro en cuanto a lo que se quiere lograr: una comprensión técnica del impacto ambiental en obras civiles, junto con la aplicación de normativa y estrategias de mitigación.", "Sí.\nEl objetivo es bastante claro en cuanto a lo que se quiere lograr: una comprensión técnica del impacto ambiental en obras civiles, junto con la aplicación de normativa y estrategias de mitigación.","Sí.\nEl objetivo es bastante claro en cuanto a lo que se quiere lograr: una comprensión técnica del impacto ambiental en obras civiles, junto con la aplicación de normativa y estrategias de mitigación."],
    "M": ["Parcialmente.\nNo establece indicadores de logro o evidencias claras de que se ha alcanzado la comprensión o la actitud crítica y responsable. Sería ideal especificar cómo se medirá: por ejemplo, mediante estudios de caso, evaluaciones prácticas o informes técnicos.", "Parcialmente.\nNo establece indicadores de logro o evidencias claras de que se ha alcanzado la comprensión o la actitud crítica y responsable. Sería ideal especificar cómo se medirá: por ejemplo, mediante estudios de caso, evaluaciones prácticas o informes técnicos.", "Parcialmente.\nNo establece indicadores de logro o evidencias claras de que se ha alcanzado la comprensión o la actitud crítica y responsable. Sería ideal especificar cómo se medirá: por ejemplo, mediante estudios de caso, evaluaciones prácticas o informes técnicos.","Parcialmente.\nNo establece indicadores de logro o evidencias claras de que se ha alcanzado la comprensión o la actitud crítica y responsable. Sería ideal especificar cómo se medirá: por ejemplo, mediante estudios de caso, evaluaciones prácticas o informes técnicos.","Parcialmente.\nNo establece indicadores de logro o evidencias claras de que se ha alcanzado la comprensión o la actitud crítica y responsable. Sería ideal especificar cómo se medirá: por ejemplo, mediante estudios de caso, evaluaciones prácticas o informes técnicos."],
    "A": ["Sí.\nParece realista para el contexto de una asignatura universitaria, siempre que se brinden los contenidos y herramientas adecuadas.", "Sí.\nParece realista para el contexto de una asignatura universitaria, siempre que se brinden los contenidos y herramientas adecuadas.", "Sí.\nParece realista para el contexto de una asignatura universitaria, siempre que se brinden los contenidos y herramientas adecuadas.", "Sí.\nParece realista para el contexto de una asignatura universitaria, siempre que se brinden los contenidos y herramientas adecuadas.","Sí.\nParece realista para el contexto de una asignatura universitaria, siempre que se brinden los contenidos y herramientas adecuadas."],
    "R": ["Sí.\nEs muy pertinente para estudiantes de ingeniería civil u otras disciplinas afines, en especial por la importancia actual del desarrollo sostenible y la normativa ambiental.", "Sí.\nEs muy pertinente para estudiantes de ingeniería civil u otras disciplinas afines, en especial por la importancia actual del desarrollo sostenible y la normativa ambiental.", "Sí.\nEs muy pertinente para estudiantes de ingeniería civil u otras disciplinas afines, en especial por la importancia actual del desarrollo sostenible y la normativa ambiental.", "Sí.\nEs muy pertinente para estudiantes de ingeniería civil u otras disciplinas afines, en especial por la importancia actual del desarrollo sostenible y la normativa ambiental.", "Sí.\nEs muy pertinente para estudiantes de ingeniería civil u otras disciplinas afines, en especial por la importancia actual del desarrollo sostenible y la normativa ambiental."],
    "T": ["No.\nEl objetivo no menciona un plazo, como por ejemplo: 'al finalizar la asignatura' o 'durante el semestre'. Esto es importante para acotar el logro en el tiempo.", "No.\nEl objetivo no menciona un plazo, como por ejemplo: 'al finalizar la asignatura' o 'durante el semestre'. Esto es importante para acotar el logro en el tiempo.", "No.\nEl objetivo no menciona un plazo, como por ejemplo: 'al finalizar la asignatura' o 'durante el semestre'. Esto es importante para acotar el logro en el tiempo.", "No.\nEl objetivo no menciona un plazo, como por ejemplo: 'al finalizar la asignatura' o 'durante el semestre'. Esto es importante para acotar el logro en el tiempo.", "No.\nEl objetivo no menciona un plazo, como por ejemplo: 'al finalizar la asignatura' o 'durante el semestre'. Esto es importante para acotar el logro en el tiempo."],
    "Objetivo Mejorado": ["Al finalizar la asignatura, el estudiante desarrollará una comprensión técnica del impacto ambiental en proyectos de infraestructura civil, aplicará la normativa vigente y estrategias de prevención y mitigación para evaluar y gestionar sus efectos durante la ejecución y mantenimiento de obras, demostrando una actitud profesional crítica y responsable frente al entorno natural mediante el análisis de casos prácticos y evaluaciones técnicas.", "Al finalizar la asignatura, el estudiante desarrollará una comprensión técnica del impacto ambiental en proyectos de infraestructura civil, aplicará la normativa vigente y estrategias de prevención y mitigación para evaluar y gestionar sus efectos durante la ejecución y mantenimiento de obras, demostrando una actitud profesional crítica y responsable frente al entorno natural mediante el análisis de casos prácticos y evaluaciones técnicas.", "Al finalizar la asignatura, el estudiante desarrollará una comprensión técnica del impacto ambiental en proyectos de infraestructura civil, aplicará la normativa vigente y estrategias de prevención y mitigación para evaluar y gestionar sus efectos durante la ejecución y mantenimiento de obras, demostrando una actitud profesional crítica y responsable frente al entorno natural mediante el análisis de casos prácticos y evaluaciones técnicas.", "Al finalizar la asignatura, el estudiante desarrollará una comprensión técnica del impacto ambiental en proyectos de infraestructura civil, aplicará la normativa vigente y estrategias de prevención y mitigación para evaluar y gestionar sus efectos durante la ejecución y mantenimiento de obras, demostrando una actitud profesional crítica y responsable frente al entorno natural mediante el análisis de casos prácticos y evaluaciones técnicas.", "Al finalizar la asignatura, el estudiante desarrollará una comprensión técnica del impacto ambiental en proyectos de infraestructura civil, aplicará la normativa vigente y estrategias de prevención y mitigación para evaluar y gestionar sus efectos durante la ejecución y mantenimiento de obras, demostrando una actitud profesional crítica y responsable frente al entorno natural mediante el análisis de casos prácticos y evaluaciones técnicas."]
}

objectivesDF = pd.DataFrame(data)

# Example usage
evaluationDF = makeTable('datos_materias.csv', objectivesDF)
print(evaluationDF.head())